spawn_helper: resolve pessimizing-move warning
spawn/test/test_spawn.cc:122:52:   required from here
spawn/include/spawn/impl/spawn.hpp:318:36: error: moving a local object in a return statement prevents copy elision [-Werror=pessimizing-move]
spawn/include/spawn/impl/spawn.hpp:318:36: note: remove ‘std::move’ call

Signed-off-by: Casey Bodley <cbodley@redhat.com>